### ISSUE TITLE
Did you ever get this to work? 

### ISSUE THREAD

**Issue by hackeresq** [garfonzo/pdf-vuer#1]
I am trying to create pdf's using a vue component and struggling. I've tried multiple methods (JSPDF with html2cavas, dom-to-image, etc). Did you ever get this to work?

**Comment by garfonzo** [comment]
No, unfortunately I did not get this to work. I have also really struggled to get some sort of PDF creation with VueJS and have come up empty. The best that I settled for was creating the "PDF" document as an HTML page, and the user simply prints to PDF. It isn't perfect, nor ideal, but it's the best I can do at this point.

**Comment by hackeresq** [comment]
Thanks for the quick response (and apologies for creating an issue for an empty repo). Figured I'd check anyway, since this is definitely something that people are looking for. 

Unfortunately, I think I've resigned myself to generate pdfs server-side using html templates -- and then display the generated PDF in Vue using [vue-pdf](https://github.com/FranckFreiburger/vue-pdf).
